version: "3.9"

services:
# edumeet
  edumeet:
    env_file: .env
    image: ${REPOSITORY}/${EDUMEET}:${TAG}
    depends_on: 
      - redis
    restart: unless-stopped
    volumes:
      - ${PWD}/configs/server:${BASEDIR}/${EDUMEET}/server/dist/config
      - ${PWD}/configs/app:${BASEDIR}/${EDUMEET}/server/dist/public/config
      - ${PWD}/certs:${BASEDIR}/${EDUMEET}/server/certs
    network_mode: "host"
    stdin_open: true
    tty: true
#   environment:
#     - DEBUG=edumeet*

  redis:
    image: redis:6
    network_mode: "host"
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    volumes:
      - ${PWD}/configs/redis:/usr/local/etc/redis