name: Edumeet CI
on: push

jobs:
  # Label of the container job
  edumeet-ci:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in 
    container: tanulasdev/edu-ci:latest
    env:
      CI: false
      TURN_API_URI: ${{ secrets.TURN_API_URI }}
      TURN_API_KEY: ${{ secrets.TURN_API_KEY }}
      EDUMEET_CI: "playwright-automated-test"

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with: 
      #     node-version: '18'
      #     cache: 'yarn'
      # - name: Setup cache
      #   uses: actions/cache@v3
      #   id: cache
      #   with:

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      # Setup env
      - name: Test env
        run: printenv EDUMEET_CI
      - name: Install app dep
        working-directory: ./app
        run: |
          yarn 
          yarn build 
      - name: Install server dep
        working-directory: ./server
        run: |
          yarn 
          yarn build-ci
      - name: Start server
        working-directory: ./server
        run: |
          yarn start & 
          sleep 5
      - name: Start app
        working-directory: ./app
        run: | 
          yarn start & 
          sleep 5
      - name: Playwright test 
        working-directory: ./app
        run: HOME=/root npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./app/playwright-report/
          retention-days: 30